### ISSUE TITLE
departure or arrival time included in a requested trip

### ISSUE THREAD

**Issue by hsp** [bytesandbrains/journeyplanner-python#1]
I am getting close having journeyplanner working as needed. 
I have just one thing left: I would like to have the departure or arrival time included in a requested trip. In the example below I manage to create the trip object with date and time as parameters, but once I iterate over (lists)  the resulting generator in the last line of code, it breaks down.
Running a debugger, up to that point, reveals that the resulting generator (myTrip) is in order, including the date and time as expected.
-----------------
from journeyplanner import JourneyPlanner, Endpoint
from datetime import datetime

client = JourneyPlanner()
dt = datetime(2019, 1, 8, 12, 0, 0)
origin = Endpoint(latitude=55.68325233, longitude=12.57150292, name="nørreport", )
destination = Endpoint(latitude=55.67271128, longitude=12.56635308, name="hovedbanen")
myTrip = client.trip(origin, destination, date=dt.date(), time=dt.time())
print(list(myTrip))

**Comment by zachasme** [comment]
The date format expected by the journeyplanner api had changed. I've released a new version (1.0.1) that fixes the problem.

**Comment by hsp** [comment]
Thanks a lot. It works perfectly.
/H.

**Comment by hsp** [comment]
If you would like t go for UTM32 coordinates rather than decimal degrees. How can that be done?

**Comment by zachasme** [comment]
Check out [pyproj](https://github.com/jswhit/pyproj). It is useful for cartographic transformations.

**Comment by hsp** [comment]
That too works greatly. Thanks

**Comment by hsp** [comment]
Is there a method in the system that can reveal the location (in coordinates) of an address (fx 'Rolighedsvej 23, 1958 Frederiksberg') or do you have to get the coords from other sources?

**Comment by Valleo4** [comment]
Hi Hans.
DAWA has a very nice API for this at dawa.aws.dk/dok/bbr.
For your specific case the documentation is located at
dawa.aws.dk/dok/bbr#find-en-bygning-ud-fra-dens-adgangsadresse.
Try dawa.aws.dk/adgangsadresser?q=Rolighedsvej%2023,%201958%20Frederiksberg
for your example.

Good day :)

Den tor. 10. jan. 2019 kl. 00.06 skrev Hans Skov-Petersen <
notifications@github.com>:

**Comment by zachasme** [comment]
There is also the `location` method in this project. It takes a string, does fuzzy search and returns coordinates.

**Comment by hsp** [comment]
it all works fine with me. Thanks a lot.
Though.. I have a problem relating to making several trips concurrently. It seems that the client breaks down (or becomes irresponsive) after 12 requests. That is when I am approaching with the anonymous client: client = JourneyPlanner(). I am trying to authorize my client using the login I am using for Rejeseplanen labs.
Something like: client.authenticate('xxx@xx.dk', 'xyzxyz’). That goofs things completely up. Is it another login/pwd I should use? Should I contact rejseplanen Labs?
Cheers
Hans

**Comment by hsp** [comment]
Hold your horses! It seem like the problem has a very different source...
Apparently no ferries are included. E.g. going to any address at Fanø from the mainland seems impossible bly public transport. The same goes for other minor islands.
I have tested the issue by the mother ship (rejseplanen.dk) at different times of the day and at future dates. I have contacted the guys and girls at Rejseplanen, but if there's another way through, pls let me know.
/Hans

**Comment by zachasme** [comment]
Hi Hans, yes you need to contact Rejseplanen to get an usable login for the client. That should reduce the rate-limiting you are experiencing. I don't know about routing by ferries, but please let us know what you find out. :-)

**Comment by hsp** [comment]
Hi Zacharias

Ok. Thanks. Until now it works with the anonymous client, I tried to compile 98x98 travel-time-matrix for two times of the week. It took 4 hours, but didn’t break down…. But I had two bypass the two locations that included small ferries.

I have been in contact with Felix at Rejseplanen, who says that they are aware of the ferrie-problem, but have no solution at present. He will inform us, once they know what to do. I’ll pass his message on when received.

Thanks again for your kind answers to all my question. ☺

Hans Skov-Petersen
Seniorforsker

University of Copenhagen
Faculty of Science
LAP
Rolighedsvej 23
DK-1958 Frederiksberg

DIR +45 +45 33 35 18 16
MOB +45 +45 23 82 80 45
hsp@ign.ku.dk<mailto:hsp@ign.ku.dk>


[cid:image001.gif@01D4B97F.54611260]

**Comment by hsp** [comment]
Can you somehow extract all transport hubs /stations, bu stops etc.) to CSV (incl. x/y-coordinates) or someting similar via the API?

**Comment by zachasme** [comment]
Not to my knowledge, no :-(
